package com.settl.backend.audit;

public enum AuditAction {
    GROUP_CREATED,
    GROUP_UPDATED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    SETTLEMENT_RECORDED,
    RECURRING_EXPENSE_CREATED,
    RECURRING_EXPENSE_TRIGGERED
}
